// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4dc_I6AcprSpybWoD3Lp_Q4S_WgTiTd0',
    appId: '1:1018644921026:web:bcac4bf03527c15d97595b',
    messagingSenderId: '1018644921026',
    projectId: 'firebaseclass25',
    authDomain: 'fir-class25.firebaseapp.com',
    storageBucket: 'firebaseclass25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7p_9cR-yR2x4qghYaIc2nI4KI4ATXjnU',
    appId: '1:1018644921026:android:2393d1b91d2f958c97595b',
    messagingSenderId: '1018644921026',
    projectId: 'firebaseclass25',
    storageBucket: 'firebaseclass25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMlTIFwULpTC2gWKX4tVCNDs95b1plf4',
    appId: '1:1018644921026:ios:e7e04091fb509c2597595b',
    messagingSenderId: '1018644921026',
    projectId: 'firebaseclass25',
    storageBucket: 'firebaseclass25.appspot.com',
    iosClientId: '1018644921026-5avqf5jp6vacnl6rlmspbdgpg60h7ep1.apps.googleusercontent.com',
    iosBundleId: 'com.example.class9',
  );
}
